#!/bin/bash

IMAGE="${IMAGE:-ghcr.io/ricardobranco777/openqa-scan:latest}"

volumes=()
if [ -f ~/.netrc ] ; then
	volumes+=(-v "$HOME/.netrc:$HOME/.netrc:ro,z")
fi

DOCKER=$(command -v docker)
PODMAN=$(command -v podman)

# We need unprivileged user namespaces for rootless containers
if unshare -U true >/dev/null 2>&1; then
	SUDO=
else
	SUDO=${SUDO:-$(command -v sudo)}
fi

# Prefer Podman over Docker since it's daemonless and we're holy
RUNTIME="${RUNTIME:-${PODMAN:-$DOCKER}}"

opts=(
	--cap-drop=ALL
	--read-only
	--rm
	--security-opt=no-new-privileges
	--user "$(id -u):$(id -g)"
)

# Do not use sudo if we're in docker group
if [[ $RUNTIME =~ docker ]]; then
	if id -Gn | grep -qw docker; then
		SUDO=
	fi
	opts+=(--net=host)
fi

if [ -n "$SUDO" ]; then
	SUDO="$SUDO --preserve-env=DEBUG"
fi

exec $SUDO "$RUNTIME" run "${opts[@]}" -e DEBUG "${volumes[@]}" "$IMAGE" "$@"
