#!/bin/bash

IMAGE="${IMAGE:-ghcr.io/ricardobranco777/openqa-scan:latest}"

volumes=()
if [ -f ~/.netrc ] ; then
	volumes+=(-v "$HOME/.netrc:$HOME/.netrc:ro,z")
fi

DOCKER=$(command -v docker)
PODMAN=$(command -v podman)

# We need unprivileged user namespaces for rootless containers
if unshare -U true >/dev/null 2>&1; then
	SUDO=
else
	SUDO=${SUDO:-$(command -v sudo)}
fi

# Use Docker if unprivileged user namespaces are disabled and
# the socket exists, otherwise use podman if available
if [ -z "$RUNTIME" ]; then
	if [ -n "$SUDO" ] && [ -S /var/run/docker.sock ]; then
		RUNTIME=$DOCKER
	else
		RUNTIME=${PODMAN:-$DOCKER}
	fi
fi

# Do not use sudo if we're in docker group
if [[ $RUNTIME =~ docker ]] && id -Gn | grep -qw docker; then
	SUDO=
fi

opts=(
	--cap-drop=ALL
	--net=host
	--read-only
	--rm
	--security-opt=no-new-privileges
	--user "$(id -u):$(id -g)"
)

if [ -n "$SUDO" ]; then
	SUDO="$SUDO --preserve-env=DEBUG"
fi

exec $SUDO "$RUNTIME" run "${opts[@]}" -e DEBUG "${volumes[@]}" "$IMAGE" "$@"
